"""
Django settings for perfumance project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url

# Cargar variables de entorno desde .env (solo si existe .env)
if os.path.exists(os.path.join(os.path.dirname(__file__), '..', '.env')):
    from dotenv import load_dotenv
    load_dotenv()
else:
    # En Railway, las variables vienen del sistema, no necesitamos load_dotenv
    try:
        from dotenv import load_dotenv
        load_dotenv()
    except:
        pass

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "dev-insecure-secret-key")


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

default_hosts = ['localhost', '127.0.0.1', '0.0.0.0']
env_hosts = [host for host in os.getenv('ALLOWED_HOSTS', '').split(',') if host]
base_url_host = ''
if os.getenv('BASE_URL'):
    try:
        from urllib.parse import urlparse
        base_url_host = urlparse(os.getenv('BASE_URL')).hostname or ''
    except Exception:
        base_url_host = ''

hosts = default_hosts + env_hosts
if base_url_host:
    hosts.append(base_url_host)
if DEBUG:
    hosts.append('testserver')
ALLOWED_HOSTS = list(dict.fromkeys(hosts))


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'adminpanel',
    'carrito',
    'catalogo',
    'usuarios',
    'ventas',
    'home',
    'ubicacion',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'perfumance.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'perfumance.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'tienda_perfumes'),
        'USER': os.getenv('DB_USER', 'admin'),
        'PASSWORD': os.getenv('DB_PASSWORD', '12345'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}

# Preferir DATABASE_URL si está presente (Railway/Heroku y otros proveedores la exponen).
database_url = os.getenv('DATABASE_URL')
if database_url:
    DATABASES['default'] = dj_database_url.config(
        default=database_url, 
        conn_max_age=600,
        conn_health_checks=True,
        ssl_require=not DEBUG
    )

# Permitir usar SQLite si se define USE_SQLITE=True (útil para desarrollo rápido)
if os.getenv('USE_SQLITE', 'False') == 'True' and not database_url:
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

if DEBUG:
    STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"
    WHITENOISE_USE_FINDERS = True
else:
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Seguridad y cabeceras para despliegues detrás de proxy (p.ej. Railway/Heroku)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SESSION_COOKIE_SECURE = os.getenv('SESSION_COOKIE_SECURE', 'False' if DEBUG else 'True') == 'True'
CSRF_COOKIE_SECURE = os.getenv('CSRF_COOKIE_SECURE', 'False' if DEBUG else 'True') == 'True'

# Configuración de sesiones - Mantener sesión al cerrar navegador
SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Guardar en base de datos
SESSION_COOKIE_AGE = 1209600  # 2 semanas en segundos (14 días)
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # NO expirar sesión al cerrar navegador
SESSION_SAVE_EVERY_REQUEST = True  # Refrescar sesión en cada petición
SESSION_COOKIE_NAME = 'perfumance_sessionid'  # Nombre personalizado de la cookie
SESSION_COOKIE_HTTPONLY = True  # Proteger cookie de JavaScript
SESSION_COOKIE_SAMESITE = 'Lax'  # Protección CSRF pero permitir navegación normal

USE_X_FORWARDED_HOST = True
CSRF_TRUSTED_ORIGINS = [origin for origin in os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',') if origin]
if os.getenv('BASE_URL') and os.getenv('BASE_URL').startswith('http'):
    CSRF_TRUSTED_ORIGINS.append(os.getenv('BASE_URL'))
if DEBUG:
    # Permitir orígenes locales en desarrollo sin ajustar el .env
    CSRF_TRUSTED_ORIGINS += [
        'http://localhost:8000',
        'http://127.0.0.1:8000',
        'http://0.0.0.0:8000',
    ]

# Google Maps Configuration
GOOGLE_MAPS_API_KEY = os.getenv('GOOGLE_MAPS_API_KEY', '')

# Contact Information
CONTACT_EMAIL = 'l221080533@iztapalapa.tecnm.mx'
CONTACT_PHONE = '+52 56 5220 6277'
CONTACT_ADDRESS = 'Av Telecomunicaciones, Chinam Pac de Juárez, Iztapalapa, 09208 Ciudad de México, CDMX, Mexico'

# Mercado Pago Configuration
MERCADO_PAGO_ACCESS_TOKEN = os.getenv('MERCADO_PAGO_ACCESS_TOKEN', '')
MERCADO_PAGO_PUBLIC_KEY = os.getenv('MERCADO_PAGO_PUBLIC_KEY', '')

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'noreply@perfumance.com')

# URLs de retorno de Mercado Pago
BASE_URL = os.getenv('BASE_URL', 'http://localhost:8000')
MERCADO_PAGO_SUCCESS_URL = f'{BASE_URL}/carrito/mercado-pago/success/'
MERCADO_PAGO_FAILURE_URL = f'{BASE_URL}/carrito/mercado-pago/failure/'
MERCADO_PAGO_PENDING_URL = f'{BASE_URL}/carrito/mercado-pago/pending/'

